"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerrainCategoryType = exports.TerrainType = void 0;
var TerrainType;
(function (TerrainType) {
    TerrainType[TerrainType["Grass"] = 0] = "Grass";
    TerrainType[TerrainType["Forest"] = 1] = "Forest";
    TerrainType[TerrainType["Building"] = 2] = "Building";
    TerrainType[TerrainType["Road"] = 3] = "Road";
    TerrainType[TerrainType["ShallowWater"] = 4] = "ShallowWater";
    TerrainType[TerrainType["DeepWater"] = 5] = "DeepWater";
    TerrainType[TerrainType["Cliff"] = 6] = "Cliff";
    TerrainType[TerrainType["Bridge"] = 7] = "Bridge";
    TerrainType[TerrainType["Snow"] = 8] = "Snow";
    TerrainType[TerrainType["Dirt"] = 9] = "Dirt";
    TerrainType[TerrainType["Sand"] = 10] = "Sand";
    TerrainType[TerrainType["Farm"] = 11] = "Farm";
    TerrainType[TerrainType["City"] = 12] = "City";
    TerrainType[TerrainType["ForestWinter"] = 13] = "ForestWinter";
    TerrainType[TerrainType["CliffWinter"] = 14] = "CliffWinter";
    TerrainType[TerrainType["RoadWinter"] = 15] = "RoadWinter";
    TerrainType[TerrainType["Ice"] = 16] = "Ice";
    TerrainType[TerrainType["FarmUnplanted"] = 17] = "FarmUnplanted";
    TerrainType[TerrainType["FarmGrowing"] = 18] = "FarmGrowing";
    TerrainType[TerrainType["Mud"] = 19] = "Mud";
    TerrainType[TerrainType["SunkenRoad"] = 20] = "SunkenRoad";
    TerrainType[TerrainType["Trench"] = 21] = "Trench";
    TerrainType[TerrainType["Redoubt"] = 22] = "Redoubt";
    TerrainType[TerrainType["Railway"] = 23] = "Railway";
    TerrainType[TerrainType["RailwayRoad"] = 24] = "RailwayRoad";
    TerrainType[TerrainType["Camp"] = 25] = "Camp";
})(TerrainType || (exports.TerrainType = TerrainType = {}));
var TerrainCategoryType;
(function (TerrainCategoryType) {
    TerrainCategoryType["Land"] = "land";
    TerrainCategoryType["Forest"] = "forest";
    TerrainCategoryType["Building"] = "building";
    TerrainCategoryType["Path"] = "path";
    TerrainCategoryType["ShallowWater"] = "shallowWater";
    TerrainCategoryType["DeepWater"] = "deepWater";
    TerrainCategoryType["Cliff"] = "cliff";
    TerrainCategoryType["Mud"] = "mud";
    TerrainCategoryType["SunkenRoad"] = "sunkenRoad";
    TerrainCategoryType["Railway"] = "railway";
    TerrainCategoryType["RailwayRoad"] = "railwayRoad";
})(TerrainCategoryType || (exports.TerrainCategoryType = TerrainCategoryType = {}));
