import { GameDataManager } from "@lob-sdk/game-data-manager";
import { Direction, Zone } from "@lob-sdk/types";
import { Point2, Vector2 } from "@lob-sdk/vector";
/**
 * Calculates the squared distance between two points.
 * This is faster than calculating the actual distance as it avoids the square root operation.
 * @param point1 - The first point.
 * @param point2 - The second point.
 * @returns The squared distance between the two points.
 */
export declare function getSquaredDistance(point1: Point2, point2: Point2): number;
/**
 * Calculates the median value from an array of numbers.
 * @param values - An array of numbers.
 * @returns The median value, or 0 if the array is empty.
 */
export declare const median: (values: number[]) => number;
/**
 * Calculates the median point from an array of points.
 * @param points - An array of points.
 * @returns A point with the median x and y coordinates.
 */
export declare const medianPoint: (points: Point2[]) => Point2;
/**
 * Divides an array into two halves.
 * @param array - The array to divide.
 * @returns A tuple containing the first half and second half of the array.
 * @template T - The type of elements in the array.
 */
export declare function divideArrayInHalf<T>(array: T[]): [T[], T[]];
/**
 * Gets the closest point inside a zone to a given point, clamping the point to the zone boundaries.
 * @param zone - The zone to clamp the point to.
 * @param point - The point to clamp.
 * @param buffer - An optional buffer value to expand the zone boundaries (default: 0).
 * @returns A Vector2 representing the closest point inside the zone.
 */
export declare const getClosestPointInsideZone: (zone: Zone, point: Point2, buffer?: number) => Vector2;
/**
 * Converts radians to degrees and ensures the result is within the range [0, 360).
 */
export declare function radiansToDegreesNormalized(radians: number): number;
/**
 * Converts degrees to radians.
 * @param degrees - The angle in degrees.
 * @returns The angle in radians.
 */
export declare function degreesToRadians(degrees: number): number;
/**
 * Converts degrees to radians with full normalization.
 * Handles values outside [0, 360) range correctly.
 * Use this when the input might be negative or > 360.
 */
export declare function degreesToRadiansNormalized(degrees: number): number;
export declare function getRandomInt(min: number, max: number, randomFn?: () => number): number;
export declare function getRandomFloat(min: number, max: number, randomFn?: () => number): number;
/**
 * Returns a number whose value is limited to the given range.
 *
 * @param {Number} value The initial value
 * @param {Number} min The lower boundary
 * @param {Number} max The upper boundary
 * @returns {Number} A number in the range (min, max)
 */
export declare const clamp: (value: number, min: number, max: number) => number;
/**
 * Recursively sets the height of tiles on a grid, ensuring smooth transitions between neighboring tiles.
 * The function propagates heights from a starting tile to its neighbors, adjusting heights to avoid abrupt changes.
 *
 * The propagation is controlled by limiting height differences between neighboring tiles to a maximum of 1.
 * Each tile is processed only once to ensure consistent height adjustments across the grid.
 */
export declare const setHeightRecursively: (x: number, y: number, height: number, heightMap: number[][]) => void;
/**
 * Packs two 8-bit coordinates (x, y) into a single 16-bit number.
 * Useful for indexing maps up to 256x256 tiles.
 */
export declare const pack2D: (x: number, y: number) => number;
/**
 * Unpacks a 16-bit key generated by `pack2D` back into its original (x, y) coordinates.
 */
export declare const unpack2D: (key: number) => {
    x: number;
    y: number;
};
/**
 * Packs four 8-bit coordinates (sourceX, sourceY, targetX, targetY) into a single 32-bit number.
 * Useful for caching line-of-sight or other relationships between two points on a map up to 256x256.
 */
export declare const pack4D: (sx: number, sy: number, tx: number, ty: number) => number;
export declare const nowInSeconds: () => number;
/**
 * Rounds a number probabilistically based on its decimal part.
 *
 * If the number is, for example, 1.1, there is a 90% chance of rounding it down to 1
 * and a 10% chance of rounding it up to 2.
 */
export declare function probabilisticRound(number: number): number;
/**
 * Checks if a collision occurs between two collision levels.
 * Returns true if both collisionLevel1 and collisionLevel2 are non-zero
 * and collisionLevel1 is greater than or equal to collisionLevel2.
 */
export declare const checkCollision: (collisionLevel1: number, collisionLevel2: number) => boolean;
/**
 * Determines the relative direction from a unit's position to a target point,
 * taking into account the unit's rotation and front/back arc configuration.
 *
 * @param from - The unit's current position (Point2 with x, y coordinates).
 * @param to - The target point to determine direction to (Point2 with x, y coordinates).
 * @param rotation - The unit's current rotation angle in radians (0 = facing right/east, π/2 = facing up/north).
 * @param frontBackArc - The angular width in radians for both the front and back arcs.
 *                       The remaining space is divided between left and right sides.
 * @returns The direction enum value: `Direction.Front`, `Direction.Back`, `Direction.Left`, or `Direction.Right`.
 */
export declare const getDirectionToPoint: (from: Point2, to: Point2, rotation: number, frontBackArc: number) => Direction;
export declare function getMaxOrgProportionDebuff(gameDataManager: GameDataManager, hpProportion: number, staminaProportion: number): number;
/**
 * Helper function to normalize an angle to be between 0 and 2π
 */
export declare function normalizeAngle(angle: number): number;
