name: LoB SDK test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0" # Specify your Node.js version

      - name: Install server dependencies
        run: npm ci

      - name: Run tests
        run: npm test
